.github/workflows/build-verification.yml, .mvn/gradle-enterprise.xml
This change enables the remote build cache for all builds. Anonymous
users have read-only build cache access, while CI has read-write.
This change also configures GitHub actions to authenticate with the
build cache.
=> Enable remote build caching

.github/workflows/build-verification.yml
Deprecation warnings appear when running actions/checkout@v2, this is fixed when upgrading to actions/checkout@v3
=> Upgrade Github actions/checkout to v3

.mvn/gradle-enterprise.xml
According to our [docs](https://docs.gradle.com/enterprise/maven-extension/#how_to_enable), this syntax should be enabled as of Gradle Enterprise Maven Extension 1.11.
=> Update goal input capture syntax

src/main/java/com/gradle/CustomGradleEnterpriseConfig.java
The commented sample code in CustomGradleEnterpriseConfig contains two lines that are outdated. This change:
- Uses the new capture API recommended as of Common Custom User Data Maven Extension 1.11
- Removes the URL configuration for the remote build cache in favor of the default built-in build cache node configuration
=> Updates to CustomGradleEnterpriseConfig commented sample code

.github/workflows/build-verification.yml
Adopt OpenJDK got moved to Eclipse Temurin and won't be updated anymore. It is highly recommended to migrate workflows from adopt to temurin to keep receiving software and security updates. See more details in the [Good-bye AdoptOpenJDK post](https://blog.adoptopenjdk.net/2021/08/goodbye-adoptopenjdk-hello-adoptium/).
=> ci: migrate to Temurin

src/main/java/com/gradle/CustomBuildScanEnhancements.java
Applies the same changes that were applied to the Gradle plugin in gradle/common-custom-user-data-gradle-plugin#150
When creating links to GitHub Actions builds, the plugin now references the environment variable GITHUB_SERVER_URL instead of hardcoding https://github.com/.
When creating build scan links to the remote repository, the plugin now uses a regex to parse out the correct url instead of hardcoding https://github.com/ or https://gitlab.com/.
1. Published plugin to maven local and resolved it using version `1.12-SNAPSHOT` ([build scan - extensions](https://ge.solutions-team.gradle.com/s/eiab67l7zcht6/extensions?details=0)). Generated correct `GitHub source` link to CCUD extension repository ([build scan - summary](https://ge.solutions-team.gradle.com/s/eiab67l7zcht6)).
2. GE …
=> Support custom links to alternate GitHub URLs

release/changes.md, src/main/java/com/gradle/Utils.java
Project properties `skipTests`, `skipITs` and `maven.test.skip` are not added as custom values by the extension when building with _Maven 4.0.0-alpha-06_ and above ([this commit](https://github.com/apache/maven/commit/a1fa3eb5346f562a745f054650eee1e84c44db30?diff=unified) changed the behavior). 
As described in the [documentation](https://maven.apache.org/ref/3.9.3/maven-embedder/cli.html) and confirmed in [the related ticket](https://issues.apache.org/jira/browse/MNG-7829), the problem is to use [session.systemProperties](https://maven.apache.org/ref/3.9.3/maven-core/apidocs/org/apache/maven/execution/MavenSession.html#getSystemProperties()) instead of [session.userProperties](https://maven.apache.org/ref/3.9.3/maven-core/apidocs/org/apache/maven/execution/MavenSession.html#getUserPropert …
=> Collect project properties from the userProperties map

release/changes.md, src/main/java/com/gradle/Utils.java, src/test/java/com/gradle/UtilsTest.java
Resolves #144 
Update `GIT_REPO_URI_PATTERN` to properly handle embedded user info in git repository URL
=> Handle embedded user info in git repo url

src/main/java/com/gradle/CustomBuildScanEnhancements.java
Corresponds to https://github.com/gradle/common-custom-user-data-gradle-plugin/pull/247
=> Capture Jenkins/Hudson urls to differentiate builds by controller

release/changes.md, src/main/java/com/gradle/CustomBuildScanEnhancements.java
Revert detached head detection as it introduces breaking changes. Will get reapplied after a minor release.
This PR reverts the following PR #198 - Improve tags/values in Jenkins and GitHub Actions when git is in a detached HEAD state
=> Revert detached head detection

release/changes.md, src/main/java/com/gradle/CustomBuildScanEnhancements.java
Reverts PR gradle/common-custom-user-data-maven-extension#199
This effectively re-applies the work done in PR https://github.com/gradle/common-custom-user-data-maven-extension/pull/198 - Improve tags/values in Jenkins and GitHub Actions when git is in a detached HEAD state
=> Reapply detached head detection

pom.xml, src/main/java/com/gradle/ccud/adapters/BuildScanApiAdapter.java, src/main/java/com/gradle/ccud/adapters/develocity/DevelocityBuildScanApiAdapter.java, src/main/java/com/gradle/ccud/adapters/enterprise/GradleEnterpriseBuildScanApiAdapter.java
In RC2, the termsOfService APIs have been renamed to termsOfUse. This commit uses the new terminology in the adapter APIs + fixes compilation errors caused by the breaking changes in the RC
=> Use "Terms of Use" terminology instead of "Terms of Service"

src/main/java/com/gradle/CustomBuildScanEnhancements.java
Fixes issue https://github.com/gradle/common-custom-user-data-maven-extension/issues/215.
Scans after the fix:
- with `export GITHUB_HEAD_REF=someBranch`: [scan](https://ge.solutions-team.gradle.com/s/gsp3eykuctwjk/custom-values#L7)
- with `export GITHUB_HEAD_REF= `: [scan](https://ge.solutions-team.gradle.com/s/eewzqm5nvryzy/custom-values)
=> Fixed empty PR branch custom value

pom.xml, release/distribution/NOTICE
This PR adds a NOTICE file to the root of the project. The NOTICE file includes the licenses of all runtime dependencies, as can be seen in [this build scan](https://ge.solutions-team.gradle.com/s/occfwoiar7gn4/dependencies?toggled=WyIwLjAiLCIwLjAtMS4xIl0#MC4wLTEuMQ).
Both the NOTICE and LICENSE files are then included in the assembled JAR.
=> NOTICE and LICENSE files are included in assembled JAR

pom.xml, src/main/java/com/gradle/CommonCustomUserDataDevelocityListener.java, src/main/java/com/gradle/CommonCustomUserDataGradleEnterpriseListener.java, src/main/resources/META-INF/sisu/javax.inject.Named
This PR removes the deprecated `@Component` annotations from the `DevelocityListener` and `GradleEnterpriseListener` classes. They have been replaced with a dedicated file at `src/main/resources/META-INF/plexus/components.xml` instead.
I verified this didn't have any impact when the extension is applied to the following Maven versions:
- 3.6.3: https://ge.solutions-team.gradle.com/s/55246cakeps4c
- 3.8.7: https://ge.solutions-team.gradle.com/s/7pcdtxe62ubvy
- 3.9.9: https://ge.solutions-team.gradle.com/s/syw4fushq7ns2
=> Deprecated Plexus @Component annotations are replaced by JSR-330 annotations

pom.xml, src/main/java/com/gradle/CommonCustomUserDataDevelocityListener.java, src/main/java/com/gradle/CommonCustomUserDataGradleEnterpriseListener.java, src/main/resources/META-INF/plexus/components.xml
The changes merged with #242 to replace the `@Component` annotations with JSR-330 annotations, didn't work and needed to be reverted. This was also missed during testing. A deeper follow up investigation is planned to be done by the Maven team.
We decided in the meantime the path of least resistance would be to revert back to the original plan to just remove the deprecated `@Component` annotations.
I have verified these changes against the following Maven versions:
- 3.3.1: https://ge.solutions-team.gradle.com/s/5v5dkvrkggnrg/extensions?expanded=WyIxIl0#2
- 3.6.3: https://ge.solutions-team.gradle.com/s/qnwt3m5qbypi4/extensions?expanded=WyIxIl0#2
- 3.8.7: https://ge.solutions-team.gradle.com/s/at5q5jj2yxio6/extensions?expanded=WyIxIl0#2
- 3.9.9: …
=> Deprecated Plexus @Component annotations are removed

pom.xml
This PR removes `repo.grdev.net` as a configured repository, which only contains RCs of the Develocity Maven extension and doesn't even contain any versions of CCUD Maven extension. This was causing Dependabot to no longer upgrade these in `pom.xml` and `.mvn/extensions.xml`.
See the commit history for `.mvn/extensions.xml` where all of a sudden Dependabot stopped updating those versions and for some reason we decided to just start manually updating it. 🙃 
https://github.com/gradle/common-custom-user-data-maven-extension/commits/main/.mvn/extensions.xml
=> Maven Central is used to resolve dependencies

.mvn/develocity.xml
The CCUDME build runs on both GitHub Actions and TeamCity. This change will correctly configure Develocity in both environments.
See [this thread](https://gradle.slack.com/archives/C011SB27MA6/p1723818756713959) for more details.
=> Use generic env var to detect CI

pom.xml, release/changes.md
This PR updates the version of Groovy used to execute the `develocity-customer-user-data.groovy` file. Without this, certain Groovy code may fail to execute when running on Java 24.
=> Update to Groovy 4

.gitignore, release/changes.md, src/main/java/com/gradle/CustomBuildScanEnhancements.java
Added VS Code detection support.
The VS Code [Maven for Java](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-maven) extension is exposing the `VSCODE_INJECTION` env var, which is used for VS Code builds detection, together with `VSCODE_PID` env var, which we've seen elsewhere. Combining these two env vars, should give us good enough coverage to cover all cases of people using VS Code.
[Here](https://ge.solutions-team.gradle.com/s/lzlsnxrrgtptq) is an example scan produced with VS Code, where the `VS Code` tag is visible.
=> Added VS Code detection support

pom.xml
The [sunset of ossrh protocol](https://central.sonatype.org/publish/publish-guide/) to publish artifacts to Maven Central requires a change in the publication process
Use the `central-publishing-maven-plugin` plugin as hinted [there](https://central.sonatype.org/publish/publish-portal-guide/)
=> Publish to Maven Central with central-publishing-maven-plugin

.github/workflows/build-verification.yml
Added a local selftest to the build-verification.yaml, same logic as we have for CCUD Gradle - see [CCUD Gradle PR](https://github.com/gradle/common-custom-user-data-gradle-plugin/pull/410).
See the [build](https://github.com/gradle/common-custom-user-data-maven-extension/actions/runs/16221456375) with these changes.
=> Added a local selftest to the build-verification.yaml

src/main/java/com/gradle/CustomBuildScanEnhancements.java
The GitHub run number is needed to precisely identify which GitHub Action run
executed the build which produced the build scan. Run ID alone is not
sufficient.
=> Add a custom value for GITHUB_RUN_NUMBER

src/main/java/com/gradle/CustomBuildScanEnhancements.java
Adds a customer value for GITHUB_RUN_ATTEMPT.
The GitHub run attempt is required to uniquely identify a workflow run.
=> Add a custom value for GITHUB_RUN_ATTEMPT
